

#The go mod tidy command is a tool that is used to automatically manage the dependencies of a Go module. When you run this command, it will add any missing dependencies, remove unused dependencies and update the go.mod file with the latest versions of the packages that are used in your project.
#

tidy:
	go mod tidy

##	github.com/multiformats/go-multihash v0.1.0 // indirect

#The -compact flag is a flag that can be used with the go mod tidy command. When this flag is used, it will make the go.mod file more compact by removing comments,
#empty lines, and unnecessary explicit versions. This flag is useful when you want to minimize the size of the go.mod file.
tidy-compact:
	go mod tidy -compact

#
#go mod tidy -v其中-v可以显示整个命令的执行过程
tidy-v:
	go mod tidy -v

