all: build




install-ganache:
	npm install -g ganache-cli

start-ganache:
	ganache-cli


#在启动ganache时，您还可以使用相同的助记词来生成相同序列的公开地址。

start-ganache:
	ganache-cli -m "much repair shock carbon improve miss forget sock include bullet interest solution"
