// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/garyxiong123/go-learn/web/go-zero/rate_limit/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/greet",
				Handler: GreetHandler(serverCtx),
			},
		},
	)
}
