###

# curl -i -X GET http://localhost:8889/from/errorCode
GET http://localhost:8889/from/code

###

GET http://localhost:8889/from/you
###
GET http://localhost:8889/from/you1

###
GET http://localhost:8889/from/panic


// how to do the request limit


// how to do the request limit for peruser
