
##go build 还有一些附加参数，可以显示更多的编译信息和更多的操作，详见下表所示
go-build:
	@echo "build test";
	go build -o myexec test.go


##上面代码中，在 go build 和文件列表之间插入了-o myexec参数，表示指定输出文件名为 myexec。
go-build-0:
	@echo "Done generate server api";
	@echo "Done generate server api";
go-run:
	 go run test.go --filename test.go

go-run-h:
	 go help run

