
new:
	goctl api new gary

go:
	goctl api go -api greet.api -dir .
doc:
	goctl api doc -dir .

style:
	goctl api go -api greet.api -dir . -style gozero

java:
	goctl api java -api greet.api -dir .

format:
	goctl api format --dir .

validate:
	goctl api validate --api greet.api



