# This Makefile is meant to be used by people that do not usually work

GOBIN?=${GOPATH}/bin

VERSION=$(shell git describe --tags)
GIT_COMMIT=$(shell git rev-parse HEAD)
GIT_COMMIT_DATE=$(shell git log -n1 --pretty='format:%cd' --date=format:'%Y%m%d')
REPO=github.com/bnb-chain/zkbnb
IMAGE_NAME=ghcr.io/bnb-chain/zkbnb


api-server:
	@echo "Done generate server api";
	@echo "Done generate server api";




##go build 还有一些附加参数，可以显示更多的编译信息和更多的操作，详见下表所示
go-build:
	@echo "Done generate server api";
	go build -o myexec main.go lib.go


##上面代码中，在 go build 和文件列表之间插入了-o myexec参数，表示指定输出文件名为 myexec。
go-build-0:
	@echo "Done generate server api";
	@echo "Done generate server api";
go build -o myexec main.go lib.go
go-run:
	@echo "Done generate server api";
	@echo "Done generate server api";
