


##会自动读取源码目录下面名为 *_test.go 的文件，生成并运行测试用的可执行文件

go-test:
	 go test


go-test-v:
	 go test -v

go-test-cover:
	 go test -cover


#-bench regexp 执行相应的 benchmarks，例如 -bench=.；
#-cover 开启测试覆盖率；
#-run regexp 只运行 regexp 匹配的函数，例如 -run=Array 那么就执行包含有 Array 开头的函数；
#-v 显示测试的详细命令。