

##清除未使用到的依赖

go-get:
	go get github.com/zeromicro/go-zero

go-list:
	go list -m all

go-list-json:
	go list -m -u -json all

go-list-h:
	go help list

##查看可下载版本
go-list-version:
	go list -m -versions github.com/garyxiong123/go-depency-A






